const levels={
  1:{name:'Tutorial',n:5,target:11,edges:[[0,1,4],[0,2,2],[1,2,1],[3,4,3],[1,3,7],[2,3,5],[2,4,8]],pos:[[18,22],[50,12],[37,49],[72,42],[84,78]]},
  2:{name:'Desafío',n:6,target:13,edges:[[0,1,3],[0,2,6],[1,2,2],[1,3,5],[2,3,3],[2,4,5],[3,4,4],[3,5,7],[4,5,1],[1,5,9]],pos:[[15,25],[45,10],[38,48],[70,28],[65,72],[90,65]]},
  3:{name:'Empates',n:6,target:19,edges:[[0,1,2],[0,2,2],[1,2,3],[1,3,4],[2,3,4],[2,4,5],[3,4,5],[3,5,6],[4,5,6],[2,5,7]],pos:[[15,25],[44,10],[37,50],[70,28],[64,75],[91,62]]},
  4:{name:'Red desconectada',n:7,target:12,edges:[[0,1,2],[1,2,3],[2,3,1],[0,3,6],[4,5,2],[5,6,4],[4,6,5]],pos:[[12,25],[34,12],[32,59],[12,78],[67,22],[88,43],[68,74]]}
};
let game;
const $=s=>document.querySelector(s);
function setup(){const data=levels[$('#level').value];game={...data,parent:Array.from({length:data.n},(_,i)=>i),rank:Array(data.n).fill(0),picked:[],rejected:[],cost:0,components:data.n,done:false};$('#welcome').hidden=true;$('#result').hidden=true;$('#game').hidden=false;render()}
function find(x){if(game.parent[x]!==x)game.parent[x]=find(game.parent[x]);return game.parent[x]}
function pick(i){if(game.done||game.picked.includes(i)||game.rejected.includes(i))return;const [u,v,w]=game.edges[i],a=find(u),b=find(v);if(a===b){game.rejected.push(i);message(`La arista ${u}–${v} crea un ciclo. Se rechaza.`,false)}else{if(game.rank[a]<game.rank[b])game.parent[a]=b;else{game.parent[b]=a;if(game.rank[a]===game.rank[b])game.rank[a]++}game.picked.push(i);game.cost+=w;game.components--;message(`¡Aceptada! Conecta dos componentes por costo ${w}.`,true)}if(game.components===1||game.picked.length+game.rejected.length===game.edges.length)finish();render()}
function finish(){game.done=true;const perfect=game.cost===game.target,forest=game.components>1;$('#result').hidden=false;$('#result').innerHTML=`<p class="eyebrow">${perfect?'RED ÓPTIMA':'RED COMPLETA'}</p><h2>${perfect?'¡Excelente, encontraste el '+(forest?'bosque mínimo':'MST')+'!':forest?'Bosque construido':'Conectaste la red'}</h2><p>Tu costo fue <strong>${game.cost}</strong>. El costo mínimo de este nivel es <strong>${game.target}</strong>. ${perfect?'Kruskal aprobaría esta solución.':'Reinicia e intenta reducir el costo evitando aristas más pesadas.'}</p><button onclick="setup()">Jugar de nuevo</button>`;message('Partida finalizada.',perfect)}
function message(t,good){const el=$('#hint');el.textContent=t;el.className='hint '+(good?'good':'bad')}
function render(){const g=$('#graph');g.innerHTML='';game.edges.forEach(([u,v,w],i)=>{const [x1,y1]=game.pos[u],[x2,y2]=game.pos[v],dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy),angle=Math.atan2(dy,dx)*180/Math.PI;const line=document.createElement('div');line.className='edge-line '+(game.picked.includes(i)?'selected':'');line.style.cssText=`left:${x1}%;top:${y1}%;width:${len}%;transform:rotate(${angle}deg)`;g.append(line);const tag=document.createElement('div');tag.className='edge-weight';tag.textContent=w;tag.style.cssText=`left:${(x1+x2)/2}%;top:${(y1+y2)/2}%`;g.append(tag)});game.pos.forEach(([x,y],i)=>{const n=document.createElement('div');n.className='node';n.textContent=i;n.style.cssText=`left:${x}%;top:${y}%`;g.append(n)});const list=$('#edge-list');list.innerHTML='';game.edges.forEach(([u,v,w],i)=>{const b=document.createElement('button');b.className='edge-btn '+(game.picked.includes(i)?'selected':game.rejected.includes(i)?'rejected':'');b.disabled=game.done||game.picked.includes(i)||game.rejected.includes(i);b.innerHTML=`<span>Nodo ${u} — Nodo ${v}</span><small>costo ${w}</small>`;b.onclick=()=>pick(i);list.append(b)});$('#cost').textContent=game.cost;$('#components').textContent=game.components;$('#chosen').textContent=game.picked.length}
$('#start').onclick=setup;$('#restart').onclick=()=>{if(game)setup();else{$('#welcome').hidden=false}};
