'use strict';
const LEVELS=[
 {n:5,edges:[[0,1,4],[0,2,2],[1,2,1],[3,4,3],[1,3,7],[2,3,5],[2,4,8]]},
 {n:6,edges:[[0,1,3],[0,2,6],[1,2,2],[1,3,5],[2,3,3],[2,4,5],[3,4,4],[3,5,7],[4,5,1],[1,5,9]]},
 {n:6,edges:[[0,1,2],[0,2,2],[1,2,3],[1,3,4],[2,3,4],[2,4,5],[3,4,5],[3,5,6],[4,5,6],[2,5,7]]},
 {n:7,edges:[[0,1,2],[1,2,3],[2,3,1],[0,3,6],[4,5,2],[5,6,4],[4,6,5]]}
];
class DSU{constructor(n){this.p=Array.from({length:n},(_,i)=>i);this.r=Array(n).fill(0);this.count=n}find(x){if(this.p[x]!==x)this.p[x]=this.find(this.p[x]);return this.p[x]}union(a,b){a=this.find(a);b=this.find(b);if(a===b)return false;if(this.r[a]<this.r[b])[a,b]=[b,a];this.p[b]=a;if(this.r[a]===this.r[b])this.r[a]++;this.count--;return true}}
const $=id=>document.getElementById(id),canvas=$('graph'),ctx=canvas.getContext('2d');
let graph,dsu,chosen,used,rejected,optimal,cost,cycles,points=[];
function mst(g){const d=new DSU(g.n),tree=[];[...g.edges].sort((a,b)=>a[2]-b[2]).forEach(e=>{if(d.union(e[0],e[1]))tree.push(e)});return tree}
function reset(){graph=LEVELS[+$('level').value];dsu=new DSU(graph.n);chosen=[];used=new Set;rejected=new Set;optimal=new Set;cost=cycles=0;$('log').innerHTML='';$('result').classList.add('hidden');$('componentsBox').style.display=$('mode').value==='training'?'block':'none';log('Nivel cargado. Selecciona una arista.');update();resize()}
function key(e){return e.join('-')}function log(s){const li=document.createElement('li');li.textContent=s;$('log').append(li);li.scrollIntoView({block:'nearest'})}
function select(i){if(used.has(i))return;used.add(i);const e=graph.edges[i];if(dsu.union(e[0],e[1])){chosen.push(e);cost+=e[2];log(`Arista ${e[0]}–${e[1]} aceptada (+${e[2]}).`)}else{cycles++;rejected.add(i);log($('mode').value==='training'?`Arista ${e[0]}–${e[1]} rechazada: cerraría un ciclo.`:'Arista rechazada.')}update();draw()}
function compare(){const tree=mst(graph),mstCost=tree.reduce((s,e)=>s+e[2],0),connected=tree.length===graph.n-1;optimal=new Set(tree.map(key));let msg;if(!connected)msg=`Este grafo está desconectado. Kruskal obtiene un bosque mínimo de costo <strong>${mstCost}</strong>.`;else if(dsu.count>1)msg=`La red todavía está incompleta. El costo mínimo posible es <strong>${mstCost}</strong>.`;else{const score=Math.max(100-5*(cost-mstCost)-10*cycles,0);const cls=score===100?'Ingeniero óptimo':score>=85?'Diseño excelente':score>=70?'Red funcional':score>=50?'Red costosa':'Requiere revisión';msg=`Costo jugador: <strong>${cost}</strong> · Costo Kruskal: <strong>${mstCost}</strong> · Puntaje: <strong>${score}</strong> (${cls}).`}$('result').innerHTML=msg;$('result').classList.remove('hidden');draw()}
function update(){$('cost').textContent=cost;$('accepted').textContent=chosen.length;$('components').textContent=dsu.count;$('cycles').textContent=cycles}
function resize(){const r=canvas.parentElement.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=r.width*d;canvas.height=r.height*d;canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';ctx.setTransform(d,0,0,d,0,0);draw()}
function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);const radius=Math.max(80,Math.min(w,h)*.38);points=Array.from({length:graph.n},(_,i)=>({x:w/2+radius*Math.cos(-Math.PI/2+2*Math.PI*i/graph.n),y:h/2+radius*Math.sin(-Math.PI/2+2*Math.PI*i/graph.n)}));graph.edges.forEach((e,i)=>{const a=points[e[0]],b=points[e[1]],k=key(e);ctx.strokeStyle=rejected.has(i)?'#fb7185':chosen.includes(e)?'#4ade80':optimal.has(k)?'#fbbf24':'#475569';ctx.lineWidth=chosen.includes(e)||optimal.has(k)?5:3;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();const x=(a.x+b.x)/2,y=(a.y+b.y)/2;ctx.fillStyle='#0b1120';ctx.beginPath();ctx.arc(x,y,13,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e5e7eb';ctx.font='bold 13px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(e[2],x,y)});points.forEach((p,i)=>{ctx.fillStyle='#172554';ctx.strokeStyle='#7dd3fc';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y,22,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 15px system-ui';ctx.fillText(i,p.x,p.y)})}
canvas.addEventListener('click',ev=>{const r=canvas.getBoundingClientRect(),x=ev.clientX-r.left,y=ev.clientY-r.top;let best=-1,dist=14;graph.edges.forEach((e,i)=>{const a=points[e[0]],b=points[e[1]],dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/(dx*dx+dy*dy))),d=Math.hypot(x-(a.x+t*dx),y-(a.y+t*dy));if(d<dist){dist=d;best=i}});if(best>=0)select(best)});
$('restart').onclick=reset;$('compare').onclick=compare;$('level').onchange=reset;$('mode').onchange=reset;new ResizeObserver(resize).observe(canvas.parentElement);reset();
